# Generated by Django 4.2.4 on 2023-08-31 12:25

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.IntegerField(unique=True)),
                ("where_from", models.TextField()),
                ("where_to", models.TextField()),
                ("create_date", models.DateTimeField()),
                ("update_date", models.DateTimeField()),
            ],
        ),
    ]
