# Generated by Django 4.2.4 on 2023-08-31 17:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="status",
            field=models.IntegerField(
                choices=[
                    ("1", "Новий"),
                    ("2", "Розміщений у поштомат"),
                    ("3", "Отриманий клієнтом"),
                    ("4", "Відмова"),
                ],
                default="1",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="create_date",
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="order",
            name="update_date",
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
