# Generated by Django 4.2.4 on 2023-08-31 17:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_order_status_alter_order_create_date_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="id",
        ),
        migrations.AlterField(
            model_name="order",
            name="number",
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
